version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend-nest
      dockerfile: Dockerfile
    container_name: merge-backend
    ports:
      - "7001:7001"
    volumes:
      - ./backend-nest/database:/app/database
    environment:
      - NODE_ENV=production
      - PORT=7001
    restart: unless-stopped
    networks:
      - app-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: merge-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database: